//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oTicket
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="oTicket.ServiceSoap")]
    public interface ServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlIslet", ReplyAction="*")]
        System.Threading.Tasks.Task<oTicket.XmlIsletResponse> XmlIsletAsync(oTicket.XmlIsletRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StrIslet", ReplyAction="*")]
        System.Threading.Tasks.Task<oTicket.StrIsletResponse> StrIsletAsync(oTicket.StrIsletRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OtobusKalkis", ReplyAction="*")]
        System.Threading.Tasks.Task<oTicket.OtobusKalkisResponse> OtobusKalkisAsync(oTicket.OtobusKalkisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDOKalkis", ReplyAction="*")]
        System.Threading.Tasks.Task<oTicket.IDOKalkisResponse> IDOKalkisAsync(oTicket.IDOKalkisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDOVaris", ReplyAction="*")]
        System.Threading.Tasks.Task<oTicket.IDOVarisResponse> IDOVarisAsync(oTicket.IDOVarisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrenNokta", ReplyAction="*")]
        System.Threading.Tasks.Task<oTicket.TrenNoktaResponse> TrenNoktaAsync(oTicket.TrenNoktaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HavaAlan", ReplyAction="*")]
        System.Threading.Tasks.Task<oTicket.HavaAlanResponse> HavaAlanAsync(oTicket.HavaAlanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResmiTatilGunleri", ReplyAction="*")]
        System.Threading.Tasks.Task<oTicket.ResmiTatilGunleriResponse> ResmiTatilGunleriAsync(oTicket.ResmiTatilGunleriRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnYakinHavaNoktaGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<oTicket.EnYakinHavaNoktaGetirResponse> EnYakinHavaNoktaGetirAsync(oTicket.EnYakinHavaNoktaGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/strEnYakinHavaNoktaGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<oTicket.strEnYakinHavaNoktaGetirResponse> strEnYakinHavaNoktaGetirAsync(oTicket.strEnYakinHavaNoktaGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnYakinKaraNoktaGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<oTicket.EnYakinKaraNoktaGetirResponse> EnYakinKaraNoktaGetirAsync(oTicket.EnYakinKaraNoktaGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/strEnYakinKaraNoktaGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<oTicket.strEnYakinKaraNoktaGetirResponse> strEnYakinKaraNoktaGetirAsync(oTicket.strEnYakinKaraNoktaGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CiftBiletKontrolEt", ReplyAction="*")]
        System.Threading.Tasks.Task<oTicket.CiftBiletKontrolEtResponse> CiftBiletKontrolEtAsync(oTicket.CiftBiletKontrolEtRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlIsletRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlIslet", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.XmlIsletRequestBody Body;
        
        public XmlIsletRequest()
        {
        }
        
        public XmlIsletRequest(oTicket.XmlIsletRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmlIsletRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement xmlIslem;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Xml.XmlElement xmlYetki;
        
        public XmlIsletRequestBody()
        {
        }
        
        public XmlIsletRequestBody(System.Xml.XmlElement xmlIslem, System.Xml.XmlElement xmlYetki)
        {
            this.xmlIslem = xmlIslem;
            this.xmlYetki = xmlYetki;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlIsletResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlIsletResponse", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.XmlIsletResponseBody Body;
        
        public XmlIsletResponse()
        {
        }
        
        public XmlIsletResponse(oTicket.XmlIsletResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmlIsletResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement XmlIsletResult;
        
        public XmlIsletResponseBody()
        {
        }
        
        public XmlIsletResponseBody(System.Xml.XmlElement XmlIsletResult)
        {
            this.XmlIsletResult = XmlIsletResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StrIsletRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StrIslet", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.StrIsletRequestBody Body;
        
        public StrIsletRequest()
        {
        }
        
        public StrIsletRequest(oTicket.StrIsletRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StrIsletRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strislem;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string stryetki;
        
        public StrIsletRequestBody()
        {
        }
        
        public StrIsletRequestBody(string strislem, string stryetki)
        {
            this.strislem = strislem;
            this.stryetki = stryetki;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StrIsletResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StrIsletResponse", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.StrIsletResponseBody Body;
        
        public StrIsletResponse()
        {
        }
        
        public StrIsletResponse(oTicket.StrIsletResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StrIsletResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StrIsletResult;
        
        public StrIsletResponseBody()
        {
        }
        
        public StrIsletResponseBody(string StrIsletResult)
        {
            this.StrIsletResult = StrIsletResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OtobusKalkisRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OtobusKalkis", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.OtobusKalkisRequestBody Body;
        
        public OtobusKalkisRequest()
        {
        }
        
        public OtobusKalkisRequest(oTicket.OtobusKalkisRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OtobusKalkisRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ilcelerGetirilsinMi;
        
        public OtobusKalkisRequestBody()
        {
        }
        
        public OtobusKalkisRequestBody(string ilcelerGetirilsinMi)
        {
            this.ilcelerGetirilsinMi = ilcelerGetirilsinMi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OtobusKalkisResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OtobusKalkisResponse", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.OtobusKalkisResponseBody Body;
        
        public OtobusKalkisResponse()
        {
        }
        
        public OtobusKalkisResponse(oTicket.OtobusKalkisResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OtobusKalkisResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement OtobusKalkisResult;
        
        public OtobusKalkisResponseBody()
        {
        }
        
        public OtobusKalkisResponseBody(System.Xml.XmlElement OtobusKalkisResult)
        {
            this.OtobusKalkisResult = OtobusKalkisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IDOKalkisRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IDOKalkis", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.IDOKalkisRequestBody Body;
        
        public IDOKalkisRequest()
        {
        }
        
        public IDOKalkisRequest(oTicket.IDOKalkisRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class IDOKalkisRequestBody
    {
        
        public IDOKalkisRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IDOKalkisResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IDOKalkisResponse", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.IDOKalkisResponseBody Body;
        
        public IDOKalkisResponse()
        {
        }
        
        public IDOKalkisResponse(oTicket.IDOKalkisResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IDOKalkisResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement IDOKalkisResult;
        
        public IDOKalkisResponseBody()
        {
        }
        
        public IDOKalkisResponseBody(System.Xml.XmlElement IDOKalkisResult)
        {
            this.IDOKalkisResult = IDOKalkisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IDOVarisRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IDOVaris", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.IDOVarisRequestBody Body;
        
        public IDOVarisRequest()
        {
        }
        
        public IDOVarisRequest(oTicket.IDOVarisRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IDOVarisRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        public IDOVarisRequestBody()
        {
        }
        
        public IDOVarisRequestBody(string key)
        {
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IDOVarisResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IDOVarisResponse", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.IDOVarisResponseBody Body;
        
        public IDOVarisResponse()
        {
        }
        
        public IDOVarisResponse(oTicket.IDOVarisResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IDOVarisResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement IDOVarisResult;
        
        public IDOVarisResponseBody()
        {
        }
        
        public IDOVarisResponseBody(System.Xml.XmlElement IDOVarisResult)
        {
            this.IDOVarisResult = IDOVarisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrenNoktaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TrenNokta", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.TrenNoktaRequestBody Body;
        
        public TrenNoktaRequest()
        {
        }
        
        public TrenNoktaRequest(oTicket.TrenNoktaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TrenNoktaRequestBody
    {
        
        public TrenNoktaRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrenNoktaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TrenNoktaResponse", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.TrenNoktaResponseBody Body;
        
        public TrenNoktaResponse()
        {
        }
        
        public TrenNoktaResponse(oTicket.TrenNoktaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TrenNoktaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement TrenNoktaResult;
        
        public TrenNoktaResponseBody()
        {
        }
        
        public TrenNoktaResponseBody(System.Xml.XmlElement TrenNoktaResult)
        {
            this.TrenNoktaResult = TrenNoktaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HavaAlanRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HavaAlan", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.HavaAlanRequestBody Body;
        
        public HavaAlanRequest()
        {
        }
        
        public HavaAlanRequest(oTicket.HavaAlanRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HavaAlanRequestBody
    {
        
        public HavaAlanRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HavaAlanResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HavaAlanResponse", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.HavaAlanResponseBody Body;
        
        public HavaAlanResponse()
        {
        }
        
        public HavaAlanResponse(oTicket.HavaAlanResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HavaAlanResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement HavaAlanResult;
        
        public HavaAlanResponseBody()
        {
        }
        
        public HavaAlanResponseBody(System.Xml.XmlElement HavaAlanResult)
        {
            this.HavaAlanResult = HavaAlanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResmiTatilGunleriRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResmiTatilGunleri", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.ResmiTatilGunleriRequestBody Body;
        
        public ResmiTatilGunleriRequest()
        {
        }
        
        public ResmiTatilGunleriRequest(oTicket.ResmiTatilGunleriRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ResmiTatilGunleriRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string yil;
        
        public ResmiTatilGunleriRequestBody()
        {
        }
        
        public ResmiTatilGunleriRequestBody(string yil)
        {
            this.yil = yil;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResmiTatilGunleriResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResmiTatilGunleriResponse", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.ResmiTatilGunleriResponseBody Body;
        
        public ResmiTatilGunleriResponse()
        {
        }
        
        public ResmiTatilGunleriResponse(oTicket.ResmiTatilGunleriResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ResmiTatilGunleriResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement ResmiTatilGunleriResult;
        
        public ResmiTatilGunleriResponseBody()
        {
        }
        
        public ResmiTatilGunleriResponseBody(System.Xml.XmlElement ResmiTatilGunleriResult)
        {
            this.ResmiTatilGunleriResult = ResmiTatilGunleriResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnYakinHavaNoktaGetirRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnYakinHavaNoktaGetir", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.EnYakinHavaNoktaGetirRequestBody Body;
        
        public EnYakinHavaNoktaGetirRequest()
        {
        }
        
        public EnYakinHavaNoktaGetirRequest(oTicket.EnYakinHavaNoktaGetirRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnYakinHavaNoktaGetirRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string karaNokta;
        
        public EnYakinHavaNoktaGetirRequestBody()
        {
        }
        
        public EnYakinHavaNoktaGetirRequestBody(string karaNokta)
        {
            this.karaNokta = karaNokta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnYakinHavaNoktaGetirResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnYakinHavaNoktaGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.EnYakinHavaNoktaGetirResponseBody Body;
        
        public EnYakinHavaNoktaGetirResponse()
        {
        }
        
        public EnYakinHavaNoktaGetirResponse(oTicket.EnYakinHavaNoktaGetirResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnYakinHavaNoktaGetirResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement EnYakinHavaNoktaGetirResult;
        
        public EnYakinHavaNoktaGetirResponseBody()
        {
        }
        
        public EnYakinHavaNoktaGetirResponseBody(System.Xml.XmlElement EnYakinHavaNoktaGetirResult)
        {
            this.EnYakinHavaNoktaGetirResult = EnYakinHavaNoktaGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class strEnYakinHavaNoktaGetirRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="strEnYakinHavaNoktaGetir", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.strEnYakinHavaNoktaGetirRequestBody Body;
        
        public strEnYakinHavaNoktaGetirRequest()
        {
        }
        
        public strEnYakinHavaNoktaGetirRequest(oTicket.strEnYakinHavaNoktaGetirRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class strEnYakinHavaNoktaGetirRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string karaNokta;
        
        public strEnYakinHavaNoktaGetirRequestBody()
        {
        }
        
        public strEnYakinHavaNoktaGetirRequestBody(string karaNokta)
        {
            this.karaNokta = karaNokta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class strEnYakinHavaNoktaGetirResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="strEnYakinHavaNoktaGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.strEnYakinHavaNoktaGetirResponseBody Body;
        
        public strEnYakinHavaNoktaGetirResponse()
        {
        }
        
        public strEnYakinHavaNoktaGetirResponse(oTicket.strEnYakinHavaNoktaGetirResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class strEnYakinHavaNoktaGetirResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strEnYakinHavaNoktaGetirResult;
        
        public strEnYakinHavaNoktaGetirResponseBody()
        {
        }
        
        public strEnYakinHavaNoktaGetirResponseBody(string strEnYakinHavaNoktaGetirResult)
        {
            this.strEnYakinHavaNoktaGetirResult = strEnYakinHavaNoktaGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnYakinKaraNoktaGetirRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnYakinKaraNoktaGetir", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.EnYakinKaraNoktaGetirRequestBody Body;
        
        public EnYakinKaraNoktaGetirRequest()
        {
        }
        
        public EnYakinKaraNoktaGetirRequest(oTicket.EnYakinKaraNoktaGetirRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnYakinKaraNoktaGetirRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string havaKod;
        
        public EnYakinKaraNoktaGetirRequestBody()
        {
        }
        
        public EnYakinKaraNoktaGetirRequestBody(string havaKod)
        {
            this.havaKod = havaKod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnYakinKaraNoktaGetirResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnYakinKaraNoktaGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.EnYakinKaraNoktaGetirResponseBody Body;
        
        public EnYakinKaraNoktaGetirResponse()
        {
        }
        
        public EnYakinKaraNoktaGetirResponse(oTicket.EnYakinKaraNoktaGetirResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnYakinKaraNoktaGetirResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnYakinKaraNoktaGetirResult;
        
        public EnYakinKaraNoktaGetirResponseBody()
        {
        }
        
        public EnYakinKaraNoktaGetirResponseBody(string EnYakinKaraNoktaGetirResult)
        {
            this.EnYakinKaraNoktaGetirResult = EnYakinKaraNoktaGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class strEnYakinKaraNoktaGetirRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="strEnYakinKaraNoktaGetir", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.strEnYakinKaraNoktaGetirRequestBody Body;
        
        public strEnYakinKaraNoktaGetirRequest()
        {
        }
        
        public strEnYakinKaraNoktaGetirRequest(oTicket.strEnYakinKaraNoktaGetirRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class strEnYakinKaraNoktaGetirRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string havaKod;
        
        public strEnYakinKaraNoktaGetirRequestBody()
        {
        }
        
        public strEnYakinKaraNoktaGetirRequestBody(string havaKod)
        {
            this.havaKod = havaKod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class strEnYakinKaraNoktaGetirResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="strEnYakinKaraNoktaGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.strEnYakinKaraNoktaGetirResponseBody Body;
        
        public strEnYakinKaraNoktaGetirResponse()
        {
        }
        
        public strEnYakinKaraNoktaGetirResponse(oTicket.strEnYakinKaraNoktaGetirResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class strEnYakinKaraNoktaGetirResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strEnYakinKaraNoktaGetirResult;
        
        public strEnYakinKaraNoktaGetirResponseBody()
        {
        }
        
        public strEnYakinKaraNoktaGetirResponseBody(string strEnYakinKaraNoktaGetirResult)
        {
            this.strEnYakinKaraNoktaGetirResult = strEnYakinKaraNoktaGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CiftBiletKontrolEtRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CiftBiletKontrolEt", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.CiftBiletKontrolEtRequestBody Body;
        
        public CiftBiletKontrolEtRequest()
        {
        }
        
        public CiftBiletKontrolEtRequest(oTicket.CiftBiletKontrolEtRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CiftBiletKontrolEtRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string islem;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int firmaNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime tarih;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string kalkis;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string varis;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string yolcuAd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string yolcuSoyad;
        
        public CiftBiletKontrolEtRequestBody()
        {
        }
        
        public CiftBiletKontrolEtRequestBody(string islem, int firmaNo, System.DateTime tarih, string kalkis, string varis, string yolcuAd, string yolcuSoyad)
        {
            this.islem = islem;
            this.firmaNo = firmaNo;
            this.tarih = tarih;
            this.kalkis = kalkis;
            this.varis = varis;
            this.yolcuAd = yolcuAd;
            this.yolcuSoyad = yolcuSoyad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CiftBiletKontrolEtResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CiftBiletKontrolEtResponse", Namespace="http://tempuri.org/", Order=0)]
        public oTicket.CiftBiletKontrolEtResponseBody Body;
        
        public CiftBiletKontrolEtResponse()
        {
        }
        
        public CiftBiletKontrolEtResponse(oTicket.CiftBiletKontrolEtResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CiftBiletKontrolEtResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CiftBiletKontrolEtResult;
        
        public CiftBiletKontrolEtResponseBody()
        {
        }
        
        public CiftBiletKontrolEtResponseBody(string CiftBiletKontrolEtResult)
        {
            this.CiftBiletKontrolEtResult = CiftBiletKontrolEtResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ServiceSoapChannel : oTicket.ServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<oTicket.ServiceSoap>, oTicket.ServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<oTicket.XmlIsletResponse> oTicket.ServiceSoap.XmlIsletAsync(oTicket.XmlIsletRequest request)
        {
            return base.Channel.XmlIsletAsync(request);
        }
        
        public System.Threading.Tasks.Task<oTicket.XmlIsletResponse> XmlIsletAsync(System.Xml.XmlElement xmlIslem, System.Xml.XmlElement xmlYetki)
        {
            oTicket.XmlIsletRequest inValue = new oTicket.XmlIsletRequest();
            inValue.Body = new oTicket.XmlIsletRequestBody();
            inValue.Body.xmlIslem = xmlIslem;
            inValue.Body.xmlYetki = xmlYetki;
            return ((oTicket.ServiceSoap)(this)).XmlIsletAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<oTicket.StrIsletResponse> oTicket.ServiceSoap.StrIsletAsync(oTicket.StrIsletRequest request)
        {
            return base.Channel.StrIsletAsync(request);
        }
        
        public System.Threading.Tasks.Task<oTicket.StrIsletResponse> StrIsletAsync(string strislem, string stryetki)
        {
            oTicket.StrIsletRequest inValue = new oTicket.StrIsletRequest();
            inValue.Body = new oTicket.StrIsletRequestBody();
            inValue.Body.strislem = strislem;
            inValue.Body.stryetki = stryetki;
            return ((oTicket.ServiceSoap)(this)).StrIsletAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<oTicket.OtobusKalkisResponse> oTicket.ServiceSoap.OtobusKalkisAsync(oTicket.OtobusKalkisRequest request)
        {
            return base.Channel.OtobusKalkisAsync(request);
        }
        
        public System.Threading.Tasks.Task<oTicket.OtobusKalkisResponse> OtobusKalkisAsync(string ilcelerGetirilsinMi)
        {
            oTicket.OtobusKalkisRequest inValue = new oTicket.OtobusKalkisRequest();
            inValue.Body = new oTicket.OtobusKalkisRequestBody();
            inValue.Body.ilcelerGetirilsinMi = ilcelerGetirilsinMi;
            return ((oTicket.ServiceSoap)(this)).OtobusKalkisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<oTicket.IDOKalkisResponse> oTicket.ServiceSoap.IDOKalkisAsync(oTicket.IDOKalkisRequest request)
        {
            return base.Channel.IDOKalkisAsync(request);
        }
        
        public System.Threading.Tasks.Task<oTicket.IDOKalkisResponse> IDOKalkisAsync()
        {
            oTicket.IDOKalkisRequest inValue = new oTicket.IDOKalkisRequest();
            inValue.Body = new oTicket.IDOKalkisRequestBody();
            return ((oTicket.ServiceSoap)(this)).IDOKalkisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<oTicket.IDOVarisResponse> oTicket.ServiceSoap.IDOVarisAsync(oTicket.IDOVarisRequest request)
        {
            return base.Channel.IDOVarisAsync(request);
        }
        
        public System.Threading.Tasks.Task<oTicket.IDOVarisResponse> IDOVarisAsync(string key)
        {
            oTicket.IDOVarisRequest inValue = new oTicket.IDOVarisRequest();
            inValue.Body = new oTicket.IDOVarisRequestBody();
            inValue.Body.key = key;
            return ((oTicket.ServiceSoap)(this)).IDOVarisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<oTicket.TrenNoktaResponse> oTicket.ServiceSoap.TrenNoktaAsync(oTicket.TrenNoktaRequest request)
        {
            return base.Channel.TrenNoktaAsync(request);
        }
        
        public System.Threading.Tasks.Task<oTicket.TrenNoktaResponse> TrenNoktaAsync()
        {
            oTicket.TrenNoktaRequest inValue = new oTicket.TrenNoktaRequest();
            inValue.Body = new oTicket.TrenNoktaRequestBody();
            return ((oTicket.ServiceSoap)(this)).TrenNoktaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<oTicket.HavaAlanResponse> oTicket.ServiceSoap.HavaAlanAsync(oTicket.HavaAlanRequest request)
        {
            return base.Channel.HavaAlanAsync(request);
        }
        
        public System.Threading.Tasks.Task<oTicket.HavaAlanResponse> HavaAlanAsync()
        {
            oTicket.HavaAlanRequest inValue = new oTicket.HavaAlanRequest();
            inValue.Body = new oTicket.HavaAlanRequestBody();
            return ((oTicket.ServiceSoap)(this)).HavaAlanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<oTicket.ResmiTatilGunleriResponse> oTicket.ServiceSoap.ResmiTatilGunleriAsync(oTicket.ResmiTatilGunleriRequest request)
        {
            return base.Channel.ResmiTatilGunleriAsync(request);
        }
        
        public System.Threading.Tasks.Task<oTicket.ResmiTatilGunleriResponse> ResmiTatilGunleriAsync(string yil)
        {
            oTicket.ResmiTatilGunleriRequest inValue = new oTicket.ResmiTatilGunleriRequest();
            inValue.Body = new oTicket.ResmiTatilGunleriRequestBody();
            inValue.Body.yil = yil;
            return ((oTicket.ServiceSoap)(this)).ResmiTatilGunleriAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<oTicket.EnYakinHavaNoktaGetirResponse> oTicket.ServiceSoap.EnYakinHavaNoktaGetirAsync(oTicket.EnYakinHavaNoktaGetirRequest request)
        {
            return base.Channel.EnYakinHavaNoktaGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<oTicket.EnYakinHavaNoktaGetirResponse> EnYakinHavaNoktaGetirAsync(string karaNokta)
        {
            oTicket.EnYakinHavaNoktaGetirRequest inValue = new oTicket.EnYakinHavaNoktaGetirRequest();
            inValue.Body = new oTicket.EnYakinHavaNoktaGetirRequestBody();
            inValue.Body.karaNokta = karaNokta;
            return ((oTicket.ServiceSoap)(this)).EnYakinHavaNoktaGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<oTicket.strEnYakinHavaNoktaGetirResponse> oTicket.ServiceSoap.strEnYakinHavaNoktaGetirAsync(oTicket.strEnYakinHavaNoktaGetirRequest request)
        {
            return base.Channel.strEnYakinHavaNoktaGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<oTicket.strEnYakinHavaNoktaGetirResponse> strEnYakinHavaNoktaGetirAsync(string karaNokta)
        {
            oTicket.strEnYakinHavaNoktaGetirRequest inValue = new oTicket.strEnYakinHavaNoktaGetirRequest();
            inValue.Body = new oTicket.strEnYakinHavaNoktaGetirRequestBody();
            inValue.Body.karaNokta = karaNokta;
            return ((oTicket.ServiceSoap)(this)).strEnYakinHavaNoktaGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<oTicket.EnYakinKaraNoktaGetirResponse> oTicket.ServiceSoap.EnYakinKaraNoktaGetirAsync(oTicket.EnYakinKaraNoktaGetirRequest request)
        {
            return base.Channel.EnYakinKaraNoktaGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<oTicket.EnYakinKaraNoktaGetirResponse> EnYakinKaraNoktaGetirAsync(string havaKod)
        {
            oTicket.EnYakinKaraNoktaGetirRequest inValue = new oTicket.EnYakinKaraNoktaGetirRequest();
            inValue.Body = new oTicket.EnYakinKaraNoktaGetirRequestBody();
            inValue.Body.havaKod = havaKod;
            return ((oTicket.ServiceSoap)(this)).EnYakinKaraNoktaGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<oTicket.strEnYakinKaraNoktaGetirResponse> oTicket.ServiceSoap.strEnYakinKaraNoktaGetirAsync(oTicket.strEnYakinKaraNoktaGetirRequest request)
        {
            return base.Channel.strEnYakinKaraNoktaGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<oTicket.strEnYakinKaraNoktaGetirResponse> strEnYakinKaraNoktaGetirAsync(string havaKod)
        {
            oTicket.strEnYakinKaraNoktaGetirRequest inValue = new oTicket.strEnYakinKaraNoktaGetirRequest();
            inValue.Body = new oTicket.strEnYakinKaraNoktaGetirRequestBody();
            inValue.Body.havaKod = havaKod;
            return ((oTicket.ServiceSoap)(this)).strEnYakinKaraNoktaGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<oTicket.CiftBiletKontrolEtResponse> oTicket.ServiceSoap.CiftBiletKontrolEtAsync(oTicket.CiftBiletKontrolEtRequest request)
        {
            return base.Channel.CiftBiletKontrolEtAsync(request);
        }
        
        public System.Threading.Tasks.Task<oTicket.CiftBiletKontrolEtResponse> CiftBiletKontrolEtAsync(string islem, int firmaNo, System.DateTime tarih, string kalkis, string varis, string yolcuAd, string yolcuSoyad)
        {
            oTicket.CiftBiletKontrolEtRequest inValue = new oTicket.CiftBiletKontrolEtRequest();
            inValue.Body = new oTicket.CiftBiletKontrolEtRequestBody();
            inValue.Body.islem = islem;
            inValue.Body.firmaNo = firmaNo;
            inValue.Body.tarih = tarih;
            inValue.Body.kalkis = kalkis;
            inValue.Body.varis = varis;
            inValue.Body.yolcuAd = yolcuAd;
            inValue.Body.yolcuSoyad = yolcuSoyad;
            return ((oTicket.ServiceSoap)(this)).CiftBiletKontrolEtAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://62.248.56.228/WSTEST/Service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://62.248.56.228/WSTEST/Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceSoap,
            
            ServiceSoap12,
        }
    }
}
